// generated by gong
import { Component, OnInit, Inject, Optional } from '@angular/core';
import { TypeofExpr } from '@angular/compiler';
import { CdkDragDrop, moveItemInArray } from '@angular/cdk/drag-drop';

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

import { Router, RouterState } from '@angular/router';
import { FormCellStringDB } from '../formcellstring-db'
import { FormCellStringService } from '../formcellstring.service'

import { FrontRepoService, FrontRepo } from '../front-repo.service'
import { NullInt64 } from '../null-int64'

@Component({
  selector: 'lib-formcellstring-sorting',
  templateUrl: './formcellstring-sorting.component.html',
  styleUrls: ['./formcellstring-sorting.component.css']
})
export class FormCellStringSortingComponent implements OnInit {

  frontRepo: FrontRepo = new (FrontRepo)

  // array of FormCellString instances that are in the association
  associatedFormCellStrings = new Array<FormCellStringDB>();

  constructor(
    private formcellstringService: FormCellStringService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of formcellstring instances
    public dialogRef: MatDialogRef<FormCellStringSortingComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {
    this.router.routeReuseStrategy.shouldReuseRoute = function () {
      return false;
    };
  }

  ngOnInit(): void {
    this.getFormCellStrings()
  }

  getFormCellStrings(): void {
    this.frontRepoService.pull(this.dialogData.GONG__StackPath).subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        let index = 0
        for (let formcellstring of this.frontRepo.FormCellStrings_array) {
          let ID = this.dialogData.ID
          let revPointerID = formcellstring[this.dialogData.ReversePointer as keyof FormCellStringDB] as unknown as NullInt64
          let revPointerID_Index = formcellstring[this.dialogData.ReversePointer + "_Index" as keyof FormCellStringDB] as unknown as NullInt64
          if (revPointerID.Int64 == ID) {
            if (revPointerID_Index == undefined) {
              revPointerID_Index = new NullInt64
              revPointerID_Index.Valid = true
              revPointerID_Index.Int64 = index++
            }
            this.associatedFormCellStrings.push(formcellstring)
          }
        }

        // sort associated formcellstring according to order
        this.associatedFormCellStrings.sort((t1, t2) => {
          let t1_revPointerID_Index = t1[this.dialogData.ReversePointer + "_Index" as keyof typeof t1] as unknown as NullInt64
          let t2_revPointerID_Index = t2[this.dialogData.ReversePointer + "_Index" as keyof typeof t2] as unknown as NullInt64
          if (t1_revPointerID_Index && t2_revPointerID_Index) {
            if (t1_revPointerID_Index.Int64 > t2_revPointerID_Index.Int64) {
              return 1;
            }
            if (t1_revPointerID_Index.Int64 < t2_revPointerID_Index.Int64) {
              return -1;
            }
          }
          return 0;
        });
      }
    )
  }

  drop(event: CdkDragDrop<string[]>) {
    moveItemInArray(this.associatedFormCellStrings, event.previousIndex, event.currentIndex);

    // set the order of FormCellString instances
    let index = 0

    for (let formcellstring of this.associatedFormCellStrings) {
      let revPointerID_Index = formcellstring[this.dialogData.ReversePointer + "_Index" as keyof FormCellStringDB] as unknown as NullInt64
      revPointerID_Index.Valid = true
      revPointerID_Index.Int64 = index++
    }
  }

  save() {

    this.associatedFormCellStrings.forEach(
      formcellstring => {
        this.formcellstringService.updateFormCellString(formcellstring, this.dialogData.GONG__StackPath)
          .subscribe(formcellstring => {
            this.formcellstringService.FormCellStringServiceChanged.next("update")
          });
      }
    )

    this.dialogRef.close('Sorting of ' + this.dialogData.ReversePointer + ' done');
  }
}
