// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional, Input } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData, FrontRepoService, FrontRepo, SelectionMode } from '../front-repo.service'
import { NullInt64 } from '../null-int64'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { ActivatedRoute, Router, RouterState } from '@angular/router';
import { FormCellBooleanDB } from '../formcellboolean-db'
import { FormCellBooleanService } from '../formcellboolean.service'

// insertion point for additional imports

import { RouteService } from '../route-service';

// TableComponent is initilizaed from different routes
// TableComponentMode detail different cases 
enum TableComponentMode {
  DISPLAY_MODE,
  ONE_MANY_ASSOCIATION_MODE,
  MANY_MANY_ASSOCIATION_MODE,
}

// generated table component
@Component({
  selector: 'app-formcellbooleanstable',
  templateUrl: './formcellbooleans-table.component.html',
  styleUrls: ['./formcellbooleans-table.component.css'],
})
export class FormCellBooleansTableComponent implements OnInit {

  @Input() GONG__StackPath: string = ""

  // mode at invocation
  mode: TableComponentMode = TableComponentMode.DISPLAY_MODE

  // used if the component is called as a selection component of FormCellBoolean instances
  selection: SelectionModel<FormCellBooleanDB> = new (SelectionModel)
  initialSelection = new Array<FormCellBooleanDB>()

  // the data source for the table
  formcellbooleans: FormCellBooleanDB[] = []
  matTableDataSource: MatTableDataSource<FormCellBooleanDB> = new (MatTableDataSource)

  // front repo, that will be referenced by this.formcellbooleans
  frontRepo: FrontRepo = new (FrontRepo)

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort)
  sort: MatSort | undefined
  @ViewChild(MatPaginator)
  paginator: MatPaginator | undefined;

  ngAfterViewInit() {

    // enable sorting on all fields (including pointers and reverse pointer)
    this.matTableDataSource.sortingDataAccessor = (formcellbooleanDB: FormCellBooleanDB, property: string) => {
      switch (property) {
        case 'ID':
          return formcellbooleanDB.ID

        // insertion point for specific sorting accessor
        case 'Name':
          return formcellbooleanDB.Name;

        case 'Value':
          return formcellbooleanDB.Value ? "true" : "false";

        default:
          console.assert(false, "Unknown field")
          return "";
      }
    };

    // enable filtering on all fields (including pointers and reverse pointer, which is not done by default)
    this.matTableDataSource.filterPredicate = (formcellbooleanDB: FormCellBooleanDB, filter: string) => {

      // filtering is based on finding a lower case filter into a concatenated string
      // the formcellbooleanDB properties
      let mergedContent = ""

      // insertion point for merging of fields
      mergedContent += formcellbooleanDB.Name.toLowerCase()

      let isSelected = mergedContent.includes(filter.toLowerCase())
      return isSelected
    };

    this.matTableDataSource.sort = this.sort!
    this.matTableDataSource.paginator = this.paginator!
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private formcellbooleanService: FormCellBooleanService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of formcellboolean instances
    public dialogRef: MatDialogRef<FormCellBooleansTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
    private activatedRoute: ActivatedRoute,

    private routeService: RouteService,
  ) {

    // compute mode
    if (dialogData == undefined) {
      this.mode = TableComponentMode.DISPLAY_MODE
    } else {
      this.GONG__StackPath = dialogData.GONG__StackPath
      switch (dialogData.SelectionMode) {
        case SelectionMode.ONE_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.ONE_MANY_ASSOCIATION_MODE
          break
        case SelectionMode.MANY_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.MANY_MANY_ASSOCIATION_MODE
          break
        default:
      }
    }

    // observable for changes in structs
    this.formcellbooleanService.FormCellBooleanServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getFormCellBooleans()
        }
      }
    )
    if (this.mode == TableComponentMode.DISPLAY_MODE) {
      this.displayedColumns = ['ID', 'Delete', // insertion point for columns to display
        "Name",
        "Value",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "Name",
        "Value",
      ]
      this.selection = new SelectionModel<FormCellBooleanDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    let stackPath = this.activatedRoute.snapshot.paramMap.get('GONG__StackPath')
    if (stackPath != undefined) {
      this.GONG__StackPath = stackPath
    }

    this.getFormCellBooleans()

    this.matTableDataSource = new MatTableDataSource(this.formcellbooleans)
  }

  getFormCellBooleans(): void {
    this.frontRepoService.pull(this.GONG__StackPath).subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        this.formcellbooleans = this.frontRepo.FormCellBooleans_array;

        // insertion point for time duration Recoveries
        // insertion point for enum int Recoveries

        // in case the component is called as a selection component
        if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {
          for (let formcellboolean of this.formcellbooleans) {
            let ID = this.dialogData.ID
            let revPointer = formcellboolean[this.dialogData.ReversePointer as keyof FormCellBooleanDB] as unknown as NullInt64
            if (revPointer.Int64 == ID) {
              this.initialSelection.push(formcellboolean)
            }
            this.selection = new SelectionModel<FormCellBooleanDB>(allowMultiSelect, this.initialSelection);
          }
        }

        if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

          let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, FormCellBooleanDB>
          let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

          // we associates on sourceInstance of type SourceStruct with a MANY MANY associations to FormCellBooleanDB
          // the field name is sourceField
          let sourceFieldArray = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]! as unknown as FormCellBooleanDB[]
          if (sourceFieldArray != null) {
            for (let associationInstance of sourceFieldArray) {
              let formcellboolean = associationInstance[this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as FormCellBooleanDB
              this.initialSelection.push(formcellboolean)
            }
          }

          this.selection = new SelectionModel<FormCellBooleanDB>(allowMultiSelect, this.initialSelection);
        }

        // update the mat table data source
        this.matTableDataSource.data = this.formcellbooleans
      }
    )
  }

  // newFormCellBoolean initiate a new formcellboolean
  // create a new FormCellBoolean objet
  newFormCellBoolean() {
  }

  deleteFormCellBoolean(formcellbooleanID: number, formcellboolean: FormCellBooleanDB) {
    // list of formcellbooleans is truncated of formcellboolean before the delete
    this.formcellbooleans = this.formcellbooleans.filter(h => h !== formcellboolean);

    this.formcellbooleanService.deleteFormCellBoolean(formcellbooleanID, this.GONG__StackPath).subscribe(
      formcellboolean => {
        this.formcellbooleanService.FormCellBooleanServiceChanged.next("delete")
      }
    );
  }

  editFormCellBoolean(formcellbooleanID: number, formcellboolean: FormCellBooleanDB) {

  }

  // set editor outlet
  setEditorRouterOutlet(formcellbooleanID: number) {
    let outletName = this.routeService.getEditorOutlet(this.GONG__StackPath)
    let fullPath = this.routeService.getPathRoot() + "-" + "formcellboolean" + "-detail"

    let outletConf: any = {}
    outletConf[outletName] = [fullPath, formcellbooleanID, this.GONG__StackPath]

    this.router.navigate([{ outlets: outletConf }])
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.formcellbooleans.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.formcellbooleans.forEach(row => this.selection.select(row));
  }

  save() {

    if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {

      let toUpdate = new Set<FormCellBooleanDB>()

      // reset all initial selection of formcellboolean that belong to formcellboolean
      for (let formcellboolean of this.initialSelection) {
        let index = formcellboolean[this.dialogData.ReversePointer as keyof FormCellBooleanDB] as unknown as NullInt64
        index.Int64 = 0
        index.Valid = true
        toUpdate.add(formcellboolean)

      }

      // from selection, set formcellboolean that belong to formcellboolean
      for (let formcellboolean of this.selection.selected) {
        let ID = this.dialogData.ID as number
        let reversePointer = formcellboolean[this.dialogData.ReversePointer as keyof FormCellBooleanDB] as unknown as NullInt64
        reversePointer.Int64 = ID
        reversePointer.Valid = true
        toUpdate.add(formcellboolean)
      }


      // update all formcellboolean (only update selection & initial selection)
      for (let formcellboolean of toUpdate) {
        this.formcellbooleanService.updateFormCellBoolean(formcellboolean, this.GONG__StackPath)
          .subscribe(formcellboolean => {
            this.formcellbooleanService.FormCellBooleanServiceChanged.next("update")
          });
      }
    }

    if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

      // get the source instance via the map of instances in the front repo
      let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, FormCellBooleanDB>
      let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

      // First, parse all instance of the association struct and remove the instance
      // that have unselect
      let unselectedFormCellBoolean = new Set<number>()
      for (let formcellboolean of this.initialSelection) {
        if (this.selection.selected.includes(formcellboolean)) {
          // console.log("formcellboolean " + formcellboolean.Name + " is still selected")
        } else {
          console.log("formcellboolean " + formcellboolean.Name + " has been unselected")
          unselectedFormCellBoolean.add(formcellboolean.ID)
          console.log("is unselected " + unselectedFormCellBoolean.has(formcellboolean.ID))
        }
      }

      // delete the association instance
      let associationInstance = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]
      let formcellboolean = associationInstance![this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as FormCellBooleanDB
      if (unselectedFormCellBoolean.has(formcellboolean.ID)) {
        this.frontRepoService.deleteService(this.dialogData.IntermediateStruct, associationInstance)


      }

      // is the source array is empty create it
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] == undefined) {
        (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] as unknown as Array<FormCellBooleanDB>) = new Array<FormCellBooleanDB>()
      }

      // second, parse all instance of the selected
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]) {
        this.selection.selected.forEach(
          formcellboolean => {
            if (!this.initialSelection.includes(formcellboolean)) {
              // console.log("formcellboolean " + formcellboolean.Name + " has been added to the selection")

              let associationInstance = {
                Name: sourceInstance["Name"] + "-" + formcellboolean.Name,
              }

              let index = associationInstance[this.dialogData.IntermediateStructField + "ID" as keyof typeof associationInstance] as unknown as NullInt64
              index.Int64 = formcellboolean.ID
              index.Valid = true

              let indexDB = associationInstance[this.dialogData.IntermediateStructField + "DBID" as keyof typeof associationInstance] as unknown as NullInt64
              indexDB.Int64 = formcellboolean.ID
              index.Valid = true

              this.frontRepoService.postService(this.dialogData.IntermediateStruct, associationInstance)

            } else {
              // console.log("formcellboolean " + formcellboolean.Name + " is still selected")
            }
          }
        )
      }

      // this.selection = new SelectionModel<FormCellBooleanDB>(allowMultiSelect, this.initialSelection);
    }

    // why pizza ?
    this.dialogRef.close('Pizza!');
  }
}
