// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional, Input } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData, FrontRepoService, FrontRepo, SelectionMode } from '../front-repo.service'
import { NullInt64 } from '../null-int64'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { ActivatedRoute, Router, RouterState } from '@angular/router';
import { FormCellDB } from '../formcell-db'
import { FormCellService } from '../formcell.service'

// insertion point for additional imports

import { RouteService } from '../route-service';

// TableComponent is initilizaed from different routes
// TableComponentMode detail different cases 
enum TableComponentMode {
  DISPLAY_MODE,
  ONE_MANY_ASSOCIATION_MODE,
  MANY_MANY_ASSOCIATION_MODE,
}

// generated table component
@Component({
  selector: 'app-formcellstable',
  templateUrl: './formcells-table.component.html',
  styleUrls: ['./formcells-table.component.css'],
})
export class FormCellsTableComponent implements OnInit {

  @Input() GONG__StackPath: string = ""

  // mode at invocation
  mode: TableComponentMode = TableComponentMode.DISPLAY_MODE

  // used if the component is called as a selection component of FormCell instances
  selection: SelectionModel<FormCellDB> = new (SelectionModel)
  initialSelection = new Array<FormCellDB>()

  // the data source for the table
  formcells: FormCellDB[] = []
  matTableDataSource: MatTableDataSource<FormCellDB> = new (MatTableDataSource)

  // front repo, that will be referenced by this.formcells
  frontRepo: FrontRepo = new (FrontRepo)

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort)
  sort: MatSort | undefined
  @ViewChild(MatPaginator)
  paginator: MatPaginator | undefined;

  ngAfterViewInit() {

    // enable sorting on all fields (including pointers and reverse pointer)
    this.matTableDataSource.sortingDataAccessor = (formcellDB: FormCellDB, property: string) => {
      switch (property) {
        case 'ID':
          return formcellDB.ID

        // insertion point for specific sorting accessor
        case 'Name':
          return formcellDB.Name;

        case 'FormCellString':
          return (formcellDB.FormCellString ? formcellDB.FormCellString.Name : '');

        case 'FormCellFloat64':
          return (formcellDB.FormCellFloat64 ? formcellDB.FormCellFloat64.Name : '');

        case 'FormCellInt':
          return (formcellDB.FormCellInt ? formcellDB.FormCellInt.Name : '');

        case 'FormCellBool':
          return (formcellDB.FormCellBool ? formcellDB.FormCellBool.Name : '');

        case 'Form_FormCells':
          if (this.frontRepo.Forms.get(formcellDB.Form_FormCellsDBID.Int64) != undefined) {
            return this.frontRepo.Forms.get(formcellDB.Form_FormCellsDBID.Int64)!.Name
          } else {
            return ""
          }

        default:
          console.assert(false, "Unknown field")
          return "";
      }
    };

    // enable filtering on all fields (including pointers and reverse pointer, which is not done by default)
    this.matTableDataSource.filterPredicate = (formcellDB: FormCellDB, filter: string) => {

      // filtering is based on finding a lower case filter into a concatenated string
      // the formcellDB properties
      let mergedContent = ""

      // insertion point for merging of fields
      mergedContent += formcellDB.Name.toLowerCase()
      if (formcellDB.FormCellString) {
        mergedContent += formcellDB.FormCellString.Name.toLowerCase()
      }
      if (formcellDB.FormCellFloat64) {
        mergedContent += formcellDB.FormCellFloat64.Name.toLowerCase()
      }
      if (formcellDB.FormCellInt) {
        mergedContent += formcellDB.FormCellInt.Name.toLowerCase()
      }
      if (formcellDB.FormCellBool) {
        mergedContent += formcellDB.FormCellBool.Name.toLowerCase()
      }
      if (formcellDB.Form_FormCellsDBID.Int64 != 0) {
        mergedContent += this.frontRepo.Forms.get(formcellDB.Form_FormCellsDBID.Int64)!.Name.toLowerCase()
      }


      let isSelected = mergedContent.includes(filter.toLowerCase())
      return isSelected
    };

    this.matTableDataSource.sort = this.sort!
    this.matTableDataSource.paginator = this.paginator!
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private formcellService: FormCellService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of formcell instances
    public dialogRef: MatDialogRef<FormCellsTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
    private activatedRoute: ActivatedRoute,

    private routeService: RouteService,
  ) {

    // compute mode
    if (dialogData == undefined) {
      this.mode = TableComponentMode.DISPLAY_MODE
    } else {
      this.GONG__StackPath = dialogData.GONG__StackPath
      switch (dialogData.SelectionMode) {
        case SelectionMode.ONE_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.ONE_MANY_ASSOCIATION_MODE
          break
        case SelectionMode.MANY_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.MANY_MANY_ASSOCIATION_MODE
          break
        default:
      }
    }

    // observable for changes in structs
    this.formcellService.FormCellServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getFormCells()
        }
      }
    )
    if (this.mode == TableComponentMode.DISPLAY_MODE) {
      this.displayedColumns = ['ID', 'Delete', // insertion point for columns to display
        "Name",
        "FormCellString",
        "FormCellFloat64",
        "FormCellInt",
        "FormCellBool",
        "Form_FormCells",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "Name",
        "FormCellString",
        "FormCellFloat64",
        "FormCellInt",
        "FormCellBool",
        "Form_FormCells",
      ]
      this.selection = new SelectionModel<FormCellDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    let stackPath = this.activatedRoute.snapshot.paramMap.get('GONG__StackPath')
    if (stackPath != undefined) {
      this.GONG__StackPath = stackPath
    }

    this.getFormCells()

    this.matTableDataSource = new MatTableDataSource(this.formcells)
  }

  getFormCells(): void {
    this.frontRepoService.pull(this.GONG__StackPath).subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        this.formcells = this.frontRepo.FormCells_array;

        // insertion point for time duration Recoveries
        // insertion point for enum int Recoveries

        // in case the component is called as a selection component
        if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {
          for (let formcell of this.formcells) {
            let ID = this.dialogData.ID
            let revPointer = formcell[this.dialogData.ReversePointer as keyof FormCellDB] as unknown as NullInt64
            if (revPointer.Int64 == ID) {
              this.initialSelection.push(formcell)
            }
            this.selection = new SelectionModel<FormCellDB>(allowMultiSelect, this.initialSelection);
          }
        }

        if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

          let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, FormCellDB>
          let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

          // we associates on sourceInstance of type SourceStruct with a MANY MANY associations to FormCellDB
          // the field name is sourceField
          let sourceFieldArray = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]! as unknown as FormCellDB[]
          if (sourceFieldArray != null) {
            for (let associationInstance of sourceFieldArray) {
              let formcell = associationInstance[this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as FormCellDB
              this.initialSelection.push(formcell)
            }
          }

          this.selection = new SelectionModel<FormCellDB>(allowMultiSelect, this.initialSelection);
        }

        // update the mat table data source
        this.matTableDataSource.data = this.formcells
      }
    )
  }

  // newFormCell initiate a new formcell
  // create a new FormCell objet
  newFormCell() {
  }

  deleteFormCell(formcellID: number, formcell: FormCellDB) {
    // list of formcells is truncated of formcell before the delete
    this.formcells = this.formcells.filter(h => h !== formcell);

    this.formcellService.deleteFormCell(formcellID, this.GONG__StackPath).subscribe(
      formcell => {
        this.formcellService.FormCellServiceChanged.next("delete")
      }
    );
  }

  editFormCell(formcellID: number, formcell: FormCellDB) {

  }

  // set editor outlet
  setEditorRouterOutlet(formcellID: number) {
    let outletName = this.routeService.getEditorOutlet(this.GONG__StackPath)
    let fullPath = this.routeService.getPathRoot() + "-" + "formcell" + "-detail"

    let outletConf: any = {}
    outletConf[outletName] = [fullPath, formcellID, this.GONG__StackPath]

    this.router.navigate([{ outlets: outletConf }])
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.formcells.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.formcells.forEach(row => this.selection.select(row));
  }

  save() {

    if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {

      let toUpdate = new Set<FormCellDB>()

      // reset all initial selection of formcell that belong to formcell
      for (let formcell of this.initialSelection) {
        let index = formcell[this.dialogData.ReversePointer as keyof FormCellDB] as unknown as NullInt64
        index.Int64 = 0
        index.Valid = true
        toUpdate.add(formcell)

      }

      // from selection, set formcell that belong to formcell
      for (let formcell of this.selection.selected) {
        let ID = this.dialogData.ID as number
        let reversePointer = formcell[this.dialogData.ReversePointer as keyof FormCellDB] as unknown as NullInt64
        reversePointer.Int64 = ID
        reversePointer.Valid = true
        toUpdate.add(formcell)
      }


      // update all formcell (only update selection & initial selection)
      for (let formcell of toUpdate) {
        this.formcellService.updateFormCell(formcell, this.GONG__StackPath)
          .subscribe(formcell => {
            this.formcellService.FormCellServiceChanged.next("update")
          });
      }
    }

    if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

      // get the source instance via the map of instances in the front repo
      let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, FormCellDB>
      let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

      // First, parse all instance of the association struct and remove the instance
      // that have unselect
      let unselectedFormCell = new Set<number>()
      for (let formcell of this.initialSelection) {
        if (this.selection.selected.includes(formcell)) {
          // console.log("formcell " + formcell.Name + " is still selected")
        } else {
          console.log("formcell " + formcell.Name + " has been unselected")
          unselectedFormCell.add(formcell.ID)
          console.log("is unselected " + unselectedFormCell.has(formcell.ID))
        }
      }

      // delete the association instance
      let associationInstance = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]
      let formcell = associationInstance![this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as FormCellDB
      if (unselectedFormCell.has(formcell.ID)) {
        this.frontRepoService.deleteService(this.dialogData.IntermediateStruct, associationInstance)


      }

      // is the source array is empty create it
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] == undefined) {
        (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] as unknown as Array<FormCellDB>) = new Array<FormCellDB>()
      }

      // second, parse all instance of the selected
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]) {
        this.selection.selected.forEach(
          formcell => {
            if (!this.initialSelection.includes(formcell)) {
              // console.log("formcell " + formcell.Name + " has been added to the selection")

              let associationInstance = {
                Name: sourceInstance["Name"] + "-" + formcell.Name,
              }

              let index = associationInstance[this.dialogData.IntermediateStructField + "ID" as keyof typeof associationInstance] as unknown as NullInt64
              index.Int64 = formcell.ID
              index.Valid = true

              let indexDB = associationInstance[this.dialogData.IntermediateStructField + "DBID" as keyof typeof associationInstance] as unknown as NullInt64
              indexDB.Int64 = formcell.ID
              index.Valid = true

              this.frontRepoService.postService(this.dialogData.IntermediateStruct, associationInstance)

            } else {
              // console.log("formcell " + formcell.Name + " is still selected")
            }
          }
        )
      }

      // this.selection = new SelectionModel<FormCellDB>(allowMultiSelect, this.initialSelection);
    }

    // why pizza ?
    this.dialogRef.close('Pizza!');
  }
}
