// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional, Input } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData, FrontRepoService, FrontRepo, SelectionMode } from '../front-repo.service'
import { NullInt64 } from '../null-int64'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { ActivatedRoute, Router, RouterState } from '@angular/router';
import { FormFieldBooleanDB } from '../formfieldboolean-db'
import { FormFieldBooleanService } from '../formfieldboolean.service'

// insertion point for additional imports

import { RouteService } from '../route-service';

// TableComponent is initilizaed from different routes
// TableComponentMode detail different cases 
enum TableComponentMode {
  DISPLAY_MODE,
  ONE_MANY_ASSOCIATION_MODE,
  MANY_MANY_ASSOCIATION_MODE,
}

// generated table component
@Component({
  selector: 'app-formfieldbooleanstable',
  templateUrl: './formfieldbooleans-table.component.html',
  styleUrls: ['./formfieldbooleans-table.component.css'],
})
export class FormFieldBooleansTableComponent implements OnInit {

  @Input() GONG__StackPath: string = ""

  // mode at invocation
  mode: TableComponentMode = TableComponentMode.DISPLAY_MODE

  // used if the component is called as a selection component of FormFieldBoolean instances
  selection: SelectionModel<FormFieldBooleanDB> = new (SelectionModel)
  initialSelection = new Array<FormFieldBooleanDB>()

  // the data source for the table
  formfieldbooleans: FormFieldBooleanDB[] = []
  matTableDataSource: MatTableDataSource<FormFieldBooleanDB> = new (MatTableDataSource)

  // front repo, that will be referenced by this.formfieldbooleans
  frontRepo: FrontRepo = new (FrontRepo)

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort)
  sort: MatSort | undefined
  @ViewChild(MatPaginator)
  paginator: MatPaginator | undefined;

  ngAfterViewInit() {

    // enable sorting on all fields (including pointers and reverse pointer)
    this.matTableDataSource.sortingDataAccessor = (formfieldbooleanDB: FormFieldBooleanDB, property: string) => {
      switch (property) {
        case 'ID':
          return formfieldbooleanDB.ID

        // insertion point for specific sorting accessor
        case 'Name':
          return formfieldbooleanDB.Name;

        case 'Value':
          return formfieldbooleanDB.Value ? "true" : "false";

        default:
          console.assert(false, "Unknown field")
          return "";
      }
    };

    // enable filtering on all fields (including pointers and reverse pointer, which is not done by default)
    this.matTableDataSource.filterPredicate = (formfieldbooleanDB: FormFieldBooleanDB, filter: string) => {

      // filtering is based on finding a lower case filter into a concatenated string
      // the formfieldbooleanDB properties
      let mergedContent = ""

      // insertion point for merging of fields
      mergedContent += formfieldbooleanDB.Name.toLowerCase()

      let isSelected = mergedContent.includes(filter.toLowerCase())
      return isSelected
    };

    this.matTableDataSource.sort = this.sort!
    this.matTableDataSource.paginator = this.paginator!
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private formfieldbooleanService: FormFieldBooleanService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of formfieldboolean instances
    public dialogRef: MatDialogRef<FormFieldBooleansTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
    private activatedRoute: ActivatedRoute,

    private routeService: RouteService,
  ) {

    // compute mode
    if (dialogData == undefined) {
      this.mode = TableComponentMode.DISPLAY_MODE
    } else {
      this.GONG__StackPath = dialogData.GONG__StackPath
      switch (dialogData.SelectionMode) {
        case SelectionMode.ONE_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.ONE_MANY_ASSOCIATION_MODE
          break
        case SelectionMode.MANY_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.MANY_MANY_ASSOCIATION_MODE
          break
        default:
      }
    }

    // observable for changes in structs
    this.formfieldbooleanService.FormFieldBooleanServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getFormFieldBooleans()
        }
      }
    )
    if (this.mode == TableComponentMode.DISPLAY_MODE) {
      this.displayedColumns = ['ID', 'Delete', // insertion point for columns to display
        "Name",
        "Value",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "Name",
        "Value",
      ]
      this.selection = new SelectionModel<FormFieldBooleanDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    let stackPath = this.activatedRoute.snapshot.paramMap.get('GONG__StackPath')
    if (stackPath != undefined) {
      this.GONG__StackPath = stackPath
    }

    this.getFormFieldBooleans()

    this.matTableDataSource = new MatTableDataSource(this.formfieldbooleans)
  }

  getFormFieldBooleans(): void {
    this.frontRepoService.pull(this.GONG__StackPath).subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        this.formfieldbooleans = this.frontRepo.FormFieldBooleans_array;

        // insertion point for time duration Recoveries
        // insertion point for enum int Recoveries

        // in case the component is called as a selection component
        if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {
          for (let formfieldboolean of this.formfieldbooleans) {
            let ID = this.dialogData.ID
            let revPointer = formfieldboolean[this.dialogData.ReversePointer as keyof FormFieldBooleanDB] as unknown as NullInt64
            if (revPointer.Int64 == ID) {
              this.initialSelection.push(formfieldboolean)
            }
            this.selection = new SelectionModel<FormFieldBooleanDB>(allowMultiSelect, this.initialSelection);
          }
        }

        if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

          let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, FormFieldBooleanDB>
          let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

          // we associates on sourceInstance of type SourceStruct with a MANY MANY associations to FormFieldBooleanDB
          // the field name is sourceField
          let sourceFieldArray = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]! as unknown as FormFieldBooleanDB[]
          if (sourceFieldArray != null) {
            for (let associationInstance of sourceFieldArray) {
              let formfieldboolean = associationInstance[this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as FormFieldBooleanDB
              this.initialSelection.push(formfieldboolean)
            }
          }

          this.selection = new SelectionModel<FormFieldBooleanDB>(allowMultiSelect, this.initialSelection);
        }

        // update the mat table data source
        this.matTableDataSource.data = this.formfieldbooleans
      }
    )
  }

  // newFormFieldBoolean initiate a new formfieldboolean
  // create a new FormFieldBoolean objet
  newFormFieldBoolean() {
  }

  deleteFormFieldBoolean(formfieldbooleanID: number, formfieldboolean: FormFieldBooleanDB) {
    // list of formfieldbooleans is truncated of formfieldboolean before the delete
    this.formfieldbooleans = this.formfieldbooleans.filter(h => h !== formfieldboolean);

    this.formfieldbooleanService.deleteFormFieldBoolean(formfieldbooleanID, this.GONG__StackPath).subscribe(
      formfieldboolean => {
        this.formfieldbooleanService.FormFieldBooleanServiceChanged.next("delete")
      }
    );
  }

  editFormFieldBoolean(formfieldbooleanID: number, formfieldboolean: FormFieldBooleanDB) {

  }

  // set editor outlet
  setEditorRouterOutlet(formfieldbooleanID: number) {
    let outletName = this.routeService.getEditorOutlet(this.GONG__StackPath)
    let fullPath = this.routeService.getPathRoot() + "-" + "formfieldboolean" + "-detail"

    let outletConf: any = {}
    outletConf[outletName] = [fullPath, formfieldbooleanID, this.GONG__StackPath]

    this.router.navigate([{ outlets: outletConf }])
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.formfieldbooleans.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.formfieldbooleans.forEach(row => this.selection.select(row));
  }

  save() {

    if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {

      let toUpdate = new Set<FormFieldBooleanDB>()

      // reset all initial selection of formfieldboolean that belong to formfieldboolean
      for (let formfieldboolean of this.initialSelection) {
        let index = formfieldboolean[this.dialogData.ReversePointer as keyof FormFieldBooleanDB] as unknown as NullInt64
        index.Int64 = 0
        index.Valid = true
        toUpdate.add(formfieldboolean)

      }

      // from selection, set formfieldboolean that belong to formfieldboolean
      for (let formfieldboolean of this.selection.selected) {
        let ID = this.dialogData.ID as number
        let reversePointer = formfieldboolean[this.dialogData.ReversePointer as keyof FormFieldBooleanDB] as unknown as NullInt64
        reversePointer.Int64 = ID
        reversePointer.Valid = true
        toUpdate.add(formfieldboolean)
      }


      // update all formfieldboolean (only update selection & initial selection)
      for (let formfieldboolean of toUpdate) {
        this.formfieldbooleanService.updateFormFieldBoolean(formfieldboolean, this.GONG__StackPath)
          .subscribe(formfieldboolean => {
            this.formfieldbooleanService.FormFieldBooleanServiceChanged.next("update")
          });
      }
    }

    if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

      // get the source instance via the map of instances in the front repo
      let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, FormFieldBooleanDB>
      let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

      // First, parse all instance of the association struct and remove the instance
      // that have unselect
      let unselectedFormFieldBoolean = new Set<number>()
      for (let formfieldboolean of this.initialSelection) {
        if (this.selection.selected.includes(formfieldboolean)) {
          // console.log("formfieldboolean " + formfieldboolean.Name + " is still selected")
        } else {
          console.log("formfieldboolean " + formfieldboolean.Name + " has been unselected")
          unselectedFormFieldBoolean.add(formfieldboolean.ID)
          console.log("is unselected " + unselectedFormFieldBoolean.has(formfieldboolean.ID))
        }
      }

      // delete the association instance
      let associationInstance = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]
      let formfieldboolean = associationInstance![this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as FormFieldBooleanDB
      if (unselectedFormFieldBoolean.has(formfieldboolean.ID)) {
        this.frontRepoService.deleteService(this.dialogData.IntermediateStruct, associationInstance)


      }

      // is the source array is empty create it
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] == undefined) {
        (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] as unknown as Array<FormFieldBooleanDB>) = new Array<FormFieldBooleanDB>()
      }

      // second, parse all instance of the selected
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]) {
        this.selection.selected.forEach(
          formfieldboolean => {
            if (!this.initialSelection.includes(formfieldboolean)) {
              // console.log("formfieldboolean " + formfieldboolean.Name + " has been added to the selection")

              let associationInstance = {
                Name: sourceInstance["Name"] + "-" + formfieldboolean.Name,
              }

              let index = associationInstance[this.dialogData.IntermediateStructField + "ID" as keyof typeof associationInstance] as unknown as NullInt64
              index.Int64 = formfieldboolean.ID
              index.Valid = true

              let indexDB = associationInstance[this.dialogData.IntermediateStructField + "DBID" as keyof typeof associationInstance] as unknown as NullInt64
              indexDB.Int64 = formfieldboolean.ID
              index.Valid = true

              this.frontRepoService.postService(this.dialogData.IntermediateStruct, associationInstance)

            } else {
              // console.log("formfieldboolean " + formfieldboolean.Name + " is still selected")
            }
          }
        )
      }

      // this.selection = new SelectionModel<FormFieldBooleanDB>(allowMultiSelect, this.initialSelection);
    }

    // why pizza ?
    this.dialogRef.close('Pizza!');
  }
}
