package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"strconv"

	gongtable_go "github.com/fullstack-lang/gongtable/go"
	gongtable_data "github.com/fullstack-lang/gongtable/go/data"
	gongtable_fullstack "github.com/fullstack-lang/gongtable/go/fullstack"
	gongtable_models "github.com/fullstack-lang/gongtable/go/models"
	gongtable_static "github.com/fullstack-lang/gongtable/go/static"

	gongdoc_load "github.com/fullstack-lang/gongdoc/go/load"
)

var (
	logGINFlag = flag.Bool("logGIN", false, "log mode for gin")

	diagrams         = flag.Bool("diagrams", true, "parse/analysis go/models and go/diagrams")
	embeddedDiagrams = flag.Bool("embeddedDiagrams", false, "parse/analysis go/models and go/embeddedDiagrams")

	port = flag.Int("port", 8080, "port server")
)

// InjectionGateway is the singloton that stores all functions
// that can set the objects the stage
// InjectionGateway stores function as a map of names
var InjectionGateway = make(map[string](func()))

// hook marhalling to stage
type BeforeCommitImplForManualyEditedTableStage struct {
}

func (impl *BeforeCommitImplForManualyEditedTableStage) BeforeCommit(stage *gongtable_models.StageStruct) {
	file, err := os.Create("./table_stage.go")
	if err != nil {
		log.Fatal(err.Error())
	}
	defer file.Close()

	stage.Checkout()
	stage.Marshall(file, "github.com/fullstack-lang/gongtable/go/models", "main")
}

type BeforeCommitImplForManualyEditedFormStage struct {
}

func (impl *BeforeCommitImplForManualyEditedFormStage) BeforeCommit(stage *gongtable_models.StageStruct) {
	file, err := os.Create("./form_stage.go")
	if err != nil {
		log.Fatal(err.Error())
	}
	defer file.Close()

	stage.Checkout()
	stage.Marshall(file, "github.com/fullstack-lang/gongtable/go/models", "main")
}

func main() {

	log.SetPrefix("gongtable: ")
	log.SetFlags(0)

	// parse program arguments
	flag.Parse()

	// setup the static file server and get the controller
	r := gongtable_static.ServeStaticFiles(*logGINFlag)

	// stageForManualyEditedTable is the stage from the code
	var stageForManualyEditedTable *gongtable_models.StageStruct
	var stageForManualyEditedForm *gongtable_models.StageStruct

	// persistence in a SQLite file on disk in memory
	stageForManualyEditedTable = gongtable_fullstack.NewStackInstance(r, "manualy filled table")
	stageForManualyEditedForm = gongtable_fullstack.NewStackInstance(r, "manualy filled form")

	// to edit the data of the stack
	gongtable_data.Load(r, gongtable_go.GoModelsDir, "manualy filled table")
	gongtable_data.Load(r, gongtable_go.GoModelsDir, "manualy filled form")

	// generated stage is the stage generated by filling data with code
	// to test performances
	generatedStage := gongtable_fullstack.NewStackInstance(r, "generated table")

	nbRows := 200
	nbColumns := 10
	table := new(gongtable_models.Table).Stage(generatedStage)
	table.Name = "Table"
	table.HasColumnSorting = true
	table.HasFiltering = true
	table.HasPaginator = true

	for j := 0; j < nbColumns; j++ {
		column := new(gongtable_models.DisplayedColumn).Stage(generatedStage)
		column.Name = fmt.Sprintf("Column %d", j)
		table.DisplayedColumns = append(table.DisplayedColumns, column)
	}

	for i := 0; i < nbRows; i++ {
		row := new(gongtable_models.Row).Stage(generatedStage)
		row.Name = fmt.Sprintf("Row %d", i)
		table.Rows = append(table.Rows, row)

		for j := 0; j < nbColumns; j++ {
			cell := new(gongtable_models.Cell).Stage(generatedStage)
			cell.Name = fmt.Sprintf("Row %d - Column %d", i, j)

			cellString := new(gongtable_models.CellString).Stage(generatedStage)
			cellString.Name = cell.Name
			cellString.Value = cell.Name
			cell.CellString = cellString

			row.Cells = append(row.Cells, cell)
		}
	}

	generatedStage.Commit()

	{
		stageForManualyEditedTable.Checkout()
		stageForManualyEditedTable.Reset()
		stageForManualyEditedTable.Commit()
		err := gongtable_models.ParseAstFile(stageForManualyEditedTable, "table_stage.go")

		// if the application is run with -unmarshallFromCode=xxx.go -marshallOnCommit
		// xxx.go might be absent the first time. However, this shall not be a show stopper.
		if err != nil {
			log.Println("no file to read " + err.Error())
		}

		stageForManualyEditedTable.Commit()
	}
	{
		stageForManualyEditedForm.Checkout()
		stageForManualyEditedForm.Reset()
		stageForManualyEditedForm.Commit()
		err := gongtable_models.ParseAstFile(stageForManualyEditedForm, "form_stage.go")

		// if the application is run with -unmarshallFromCode=xxx.go -marshallOnCommit
		// xxx.go might be absent the first time. However, this shall not be a show stopper.
		if err != nil {
			log.Println("no file to read " + err.Error())
		}

		stageForManualyEditedForm.Commit()
	}

	// hook automatic marshall to go code at every commit
	{
		hook := new(BeforeCommitImplForManualyEditedTableStage)
		stageForManualyEditedTable.OnInitCommitFromFrontCallback = hook
	}
	{
		hook := new(BeforeCommitImplForManualyEditedFormStage)
		stageForManualyEditedForm.OnInitCommitFromFrontCallback = hook
	}

	gongdoc_load.Load(
		"gongtable",
		"github.com/fullstack-lang/gongtable/go/models",
		gongtable_go.GoModelsDir,
		gongtable_go.GoDiagramsDir,
		r,
		*embeddedDiagrams,
		&stageForManualyEditedTable.Map_GongStructName_InstancesNb)

	log.Printf("Server ready serve on localhost:" + strconv.Itoa(*port))
	err := r.Run(":" + strconv.Itoa(*port))
	if err != nil {
		log.Fatalln(err.Error())
	}
}
