// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional, Input } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData, FrontRepoService, FrontRepo, SelectionMode } from '../front-repo.service'
import { NullInt64 } from '../null-int64'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { ActivatedRoute, Router, RouterState } from '@angular/router';
import { FormCellStringDB } from '../formcellstring-db'
import { FormCellStringService } from '../formcellstring.service'

// insertion point for additional imports

import { RouteService } from '../route-service';

// TableComponent is initilizaed from different routes
// TableComponentMode detail different cases 
enum TableComponentMode {
  DISPLAY_MODE,
  ONE_MANY_ASSOCIATION_MODE,
  MANY_MANY_ASSOCIATION_MODE,
}

// generated table component
@Component({
  selector: 'app-formcellstringstable',
  templateUrl: './formcellstrings-table.component.html',
  styleUrls: ['./formcellstrings-table.component.css'],
})
export class FormCellStringsTableComponent implements OnInit {

  @Input() GONG__StackPath: string = ""

  // mode at invocation
  mode: TableComponentMode = TableComponentMode.DISPLAY_MODE

  // used if the component is called as a selection component of FormCellString instances
  selection: SelectionModel<FormCellStringDB> = new (SelectionModel)
  initialSelection = new Array<FormCellStringDB>()

  // the data source for the table
  formcellstrings: FormCellStringDB[] = []
  matTableDataSource: MatTableDataSource<FormCellStringDB> = new (MatTableDataSource)

  // front repo, that will be referenced by this.formcellstrings
  frontRepo: FrontRepo = new (FrontRepo)

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort)
  sort: MatSort | undefined
  @ViewChild(MatPaginator)
  paginator: MatPaginator | undefined;

  ngAfterViewInit() {

    // enable sorting on all fields (including pointers and reverse pointer)
    this.matTableDataSource.sortingDataAccessor = (formcellstringDB: FormCellStringDB, property: string) => {
      switch (property) {
        case 'ID':
          return formcellstringDB.ID

        // insertion point for specific sorting accessor
        case 'Name':
          return formcellstringDB.Name;

        case 'Value':
          return formcellstringDB.Value;

        default:
          console.assert(false, "Unknown field")
          return "";
      }
    };

    // enable filtering on all fields (including pointers and reverse pointer, which is not done by default)
    this.matTableDataSource.filterPredicate = (formcellstringDB: FormCellStringDB, filter: string) => {

      // filtering is based on finding a lower case filter into a concatenated string
      // the formcellstringDB properties
      let mergedContent = ""

      // insertion point for merging of fields
      mergedContent += formcellstringDB.Name.toLowerCase()
      mergedContent += formcellstringDB.Value.toLowerCase()

      let isSelected = mergedContent.includes(filter.toLowerCase())
      return isSelected
    };

    this.matTableDataSource.sort = this.sort!
    this.matTableDataSource.paginator = this.paginator!
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private formcellstringService: FormCellStringService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of formcellstring instances
    public dialogRef: MatDialogRef<FormCellStringsTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
    private activatedRoute: ActivatedRoute,

    private routeService: RouteService,
  ) {

    // compute mode
    if (dialogData == undefined) {
      this.mode = TableComponentMode.DISPLAY_MODE
    } else {
      this.GONG__StackPath = dialogData.GONG__StackPath
      switch (dialogData.SelectionMode) {
        case SelectionMode.ONE_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.ONE_MANY_ASSOCIATION_MODE
          break
        case SelectionMode.MANY_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.MANY_MANY_ASSOCIATION_MODE
          break
        default:
      }
    }

    // observable for changes in structs
    this.formcellstringService.FormCellStringServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getFormCellStrings()
        }
      }
    )
    if (this.mode == TableComponentMode.DISPLAY_MODE) {
      this.displayedColumns = ['ID', 'Delete', // insertion point for columns to display
        "Name",
        "Value",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "Name",
        "Value",
      ]
      this.selection = new SelectionModel<FormCellStringDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    let stackPath = this.activatedRoute.snapshot.paramMap.get('GONG__StackPath')
    if (stackPath != undefined) {
      this.GONG__StackPath = stackPath
    }

    this.getFormCellStrings()

    this.matTableDataSource = new MatTableDataSource(this.formcellstrings)
  }

  getFormCellStrings(): void {
    this.frontRepoService.pull(this.GONG__StackPath).subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        this.formcellstrings = this.frontRepo.FormCellStrings_array;

        // insertion point for time duration Recoveries
        // insertion point for enum int Recoveries

        // in case the component is called as a selection component
        if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {
          for (let formcellstring of this.formcellstrings) {
            let ID = this.dialogData.ID
            let revPointer = formcellstring[this.dialogData.ReversePointer as keyof FormCellStringDB] as unknown as NullInt64
            if (revPointer.Int64 == ID) {
              this.initialSelection.push(formcellstring)
            }
            this.selection = new SelectionModel<FormCellStringDB>(allowMultiSelect, this.initialSelection);
          }
        }

        if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

          let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, FormCellStringDB>
          let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

          // we associates on sourceInstance of type SourceStruct with a MANY MANY associations to FormCellStringDB
          // the field name is sourceField
          let sourceFieldArray = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]! as unknown as FormCellStringDB[]
          if (sourceFieldArray != null) {
            for (let associationInstance of sourceFieldArray) {
              let formcellstring = associationInstance[this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as FormCellStringDB
              this.initialSelection.push(formcellstring)
            }
          }

          this.selection = new SelectionModel<FormCellStringDB>(allowMultiSelect, this.initialSelection);
        }

        // update the mat table data source
        this.matTableDataSource.data = this.formcellstrings
      }
    )
  }

  // newFormCellString initiate a new formcellstring
  // create a new FormCellString objet
  newFormCellString() {
  }

  deleteFormCellString(formcellstringID: number, formcellstring: FormCellStringDB) {
    // list of formcellstrings is truncated of formcellstring before the delete
    this.formcellstrings = this.formcellstrings.filter(h => h !== formcellstring);

    this.formcellstringService.deleteFormCellString(formcellstringID, this.GONG__StackPath).subscribe(
      formcellstring => {
        this.formcellstringService.FormCellStringServiceChanged.next("delete")
      }
    );
  }

  editFormCellString(formcellstringID: number, formcellstring: FormCellStringDB) {

  }

  // set editor outlet
  setEditorRouterOutlet(formcellstringID: number) {
    let outletName = this.routeService.getEditorOutlet(this.GONG__StackPath)
    let fullPath = this.routeService.getPathRoot() + "-" + "formcellstring" + "-detail"

    let outletConf: any = {}
    outletConf[outletName] = [fullPath, formcellstringID, this.GONG__StackPath]

    this.router.navigate([{ outlets: outletConf }])
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.formcellstrings.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.formcellstrings.forEach(row => this.selection.select(row));
  }

  save() {

    if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {

      let toUpdate = new Set<FormCellStringDB>()

      // reset all initial selection of formcellstring that belong to formcellstring
      for (let formcellstring of this.initialSelection) {
        let index = formcellstring[this.dialogData.ReversePointer as keyof FormCellStringDB] as unknown as NullInt64
        index.Int64 = 0
        index.Valid = true
        toUpdate.add(formcellstring)

      }

      // from selection, set formcellstring that belong to formcellstring
      for (let formcellstring of this.selection.selected) {
        let ID = this.dialogData.ID as number
        let reversePointer = formcellstring[this.dialogData.ReversePointer as keyof FormCellStringDB] as unknown as NullInt64
        reversePointer.Int64 = ID
        reversePointer.Valid = true
        toUpdate.add(formcellstring)
      }


      // update all formcellstring (only update selection & initial selection)
      for (let formcellstring of toUpdate) {
        this.formcellstringService.updateFormCellString(formcellstring, this.GONG__StackPath)
          .subscribe(formcellstring => {
            this.formcellstringService.FormCellStringServiceChanged.next("update")
          });
      }
    }

    if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

      // get the source instance via the map of instances in the front repo
      let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, FormCellStringDB>
      let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

      // First, parse all instance of the association struct and remove the instance
      // that have unselect
      let unselectedFormCellString = new Set<number>()
      for (let formcellstring of this.initialSelection) {
        if (this.selection.selected.includes(formcellstring)) {
          // console.log("formcellstring " + formcellstring.Name + " is still selected")
        } else {
          console.log("formcellstring " + formcellstring.Name + " has been unselected")
          unselectedFormCellString.add(formcellstring.ID)
          console.log("is unselected " + unselectedFormCellString.has(formcellstring.ID))
        }
      }

      // delete the association instance
      let associationInstance = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]
      let formcellstring = associationInstance![this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as FormCellStringDB
      if (unselectedFormCellString.has(formcellstring.ID)) {
        this.frontRepoService.deleteService(this.dialogData.IntermediateStruct, associationInstance)


      }

      // is the source array is empty create it
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] == undefined) {
        (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] as unknown as Array<FormCellStringDB>) = new Array<FormCellStringDB>()
      }

      // second, parse all instance of the selected
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]) {
        this.selection.selected.forEach(
          formcellstring => {
            if (!this.initialSelection.includes(formcellstring)) {
              // console.log("formcellstring " + formcellstring.Name + " has been added to the selection")

              let associationInstance = {
                Name: sourceInstance["Name"] + "-" + formcellstring.Name,
              }

              let index = associationInstance[this.dialogData.IntermediateStructField + "ID" as keyof typeof associationInstance] as unknown as NullInt64
              index.Int64 = formcellstring.ID
              index.Valid = true

              let indexDB = associationInstance[this.dialogData.IntermediateStructField + "DBID" as keyof typeof associationInstance] as unknown as NullInt64
              indexDB.Int64 = formcellstring.ID
              index.Valid = true

              this.frontRepoService.postService(this.dialogData.IntermediateStruct, associationInstance)

            } else {
              // console.log("formcellstring " + formcellstring.Name + " is still selected")
            }
          }
        )
      }

      // this.selection = new SelectionModel<FormCellStringDB>(allowMultiSelect, this.initialSelection);
    }

    // why pizza ?
    this.dialogRef.close('Pizza!');
  }
}
