// generated by gong
import { Component, OnInit, Inject, Optional } from '@angular/core';
import { TypeofExpr } from '@angular/compiler';
import { CdkDragDrop, moveItemInArray } from '@angular/cdk/drag-drop';

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

import { Router, RouterState } from '@angular/router';
import { FormCellIntDB } from '../formcellint-db'
import { FormCellIntService } from '../formcellint.service'

import { FrontRepoService, FrontRepo } from '../front-repo.service'
import { NullInt64 } from '../null-int64'

@Component({
  selector: 'lib-formcellint-sorting',
  templateUrl: './formcellint-sorting.component.html',
  styleUrls: ['./formcellint-sorting.component.css']
})
export class FormCellIntSortingComponent implements OnInit {

  frontRepo: FrontRepo = new (FrontRepo)

  // array of FormCellInt instances that are in the association
  associatedFormCellInts = new Array<FormCellIntDB>();

  constructor(
    private formcellintService: FormCellIntService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of formcellint instances
    public dialogRef: MatDialogRef<FormCellIntSortingComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {
    this.router.routeReuseStrategy.shouldReuseRoute = function () {
      return false;
    };
  }

  ngOnInit(): void {
    this.getFormCellInts()
  }

  getFormCellInts(): void {
    this.frontRepoService.pull(this.dialogData.GONG__StackPath).subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        let index = 0
        for (let formcellint of this.frontRepo.FormCellInts_array) {
          let ID = this.dialogData.ID
          let revPointerID = formcellint[this.dialogData.ReversePointer as keyof FormCellIntDB] as unknown as NullInt64
          let revPointerID_Index = formcellint[this.dialogData.ReversePointer + "_Index" as keyof FormCellIntDB] as unknown as NullInt64
          if (revPointerID.Int64 == ID) {
            if (revPointerID_Index == undefined) {
              revPointerID_Index = new NullInt64
              revPointerID_Index.Valid = true
              revPointerID_Index.Int64 = index++
            }
            this.associatedFormCellInts.push(formcellint)
          }
        }

        // sort associated formcellint according to order
        this.associatedFormCellInts.sort((t1, t2) => {
          let t1_revPointerID_Index = t1[this.dialogData.ReversePointer + "_Index" as keyof typeof t1] as unknown as NullInt64
          let t2_revPointerID_Index = t2[this.dialogData.ReversePointer + "_Index" as keyof typeof t2] as unknown as NullInt64
          if (t1_revPointerID_Index && t2_revPointerID_Index) {
            if (t1_revPointerID_Index.Int64 > t2_revPointerID_Index.Int64) {
              return 1;
            }
            if (t1_revPointerID_Index.Int64 < t2_revPointerID_Index.Int64) {
              return -1;
            }
          }
          return 0;
        });
      }
    )
  }

  drop(event: CdkDragDrop<string[]>) {
    moveItemInArray(this.associatedFormCellInts, event.previousIndex, event.currentIndex);

    // set the order of FormCellInt instances
    let index = 0

    for (let formcellint of this.associatedFormCellInts) {
      let revPointerID_Index = formcellint[this.dialogData.ReversePointer + "_Index" as keyof FormCellIntDB] as unknown as NullInt64
      revPointerID_Index.Valid = true
      revPointerID_Index.Int64 = index++
    }
  }

  save() {

    this.associatedFormCellInts.forEach(
      formcellint => {
        this.formcellintService.updateFormCellInt(formcellint, this.dialogData.GONG__StackPath)
          .subscribe(formcellint => {
            this.formcellintService.FormCellIntServiceChanged.next("update")
          });
      }
    )

    this.dialogRef.close('Sorting of ' + this.dialogData.ReversePointer + ' done');
  }
}
