// generated by gong
import { Component, OnInit, Inject, Optional } from '@angular/core';
import { TypeofExpr } from '@angular/compiler';
import { CdkDragDrop, moveItemInArray } from '@angular/cdk/drag-drop';

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

import { Router, RouterState } from '@angular/router';
import { FormDB } from '../form-db'
import { FormService } from '../form.service'

import { FrontRepoService, FrontRepo } from '../front-repo.service'
import { NullInt64 } from '../null-int64'

@Component({
  selector: 'lib-form-sorting',
  templateUrl: './form-sorting.component.html',
  styleUrls: ['./form-sorting.component.css']
})
export class FormSortingComponent implements OnInit {

  frontRepo: FrontRepo = new (FrontRepo)

  // array of Form instances that are in the association
  associatedForms = new Array<FormDB>();

  constructor(
    private formService: FormService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of form instances
    public dialogRef: MatDialogRef<FormSortingComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {
    this.router.routeReuseStrategy.shouldReuseRoute = function () {
      return false;
    };
  }

  ngOnInit(): void {
    this.getForms()
  }

  getForms(): void {
    this.frontRepoService.pull(this.dialogData.GONG__StackPath).subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        let index = 0
        for (let form of this.frontRepo.Forms_array) {
          let ID = this.dialogData.ID
          let revPointerID = form[this.dialogData.ReversePointer as keyof FormDB] as unknown as NullInt64
          let revPointerID_Index = form[this.dialogData.ReversePointer + "_Index" as keyof FormDB] as unknown as NullInt64
          if (revPointerID.Int64 == ID) {
            if (revPointerID_Index == undefined) {
              revPointerID_Index = new NullInt64
              revPointerID_Index.Valid = true
              revPointerID_Index.Int64 = index++
            }
            this.associatedForms.push(form)
          }
        }

        // sort associated form according to order
        this.associatedForms.sort((t1, t2) => {
          let t1_revPointerID_Index = t1[this.dialogData.ReversePointer + "_Index" as keyof typeof t1] as unknown as NullInt64
          let t2_revPointerID_Index = t2[this.dialogData.ReversePointer + "_Index" as keyof typeof t2] as unknown as NullInt64
          if (t1_revPointerID_Index && t2_revPointerID_Index) {
            if (t1_revPointerID_Index.Int64 > t2_revPointerID_Index.Int64) {
              return 1;
            }
            if (t1_revPointerID_Index.Int64 < t2_revPointerID_Index.Int64) {
              return -1;
            }
          }
          return 0;
        });
      }
    )
  }

  drop(event: CdkDragDrop<string[]>) {
    moveItemInArray(this.associatedForms, event.previousIndex, event.currentIndex);

    // set the order of Form instances
    let index = 0

    for (let form of this.associatedForms) {
      let revPointerID_Index = form[this.dialogData.ReversePointer + "_Index" as keyof FormDB] as unknown as NullInt64
      revPointerID_Index.Valid = true
      revPointerID_Index.Int64 = index++
    }
  }

  save() {

    this.associatedForms.forEach(
      form => {
        this.formService.updateForm(form, this.dialogData.GONG__StackPath)
          .subscribe(form => {
            this.formService.FormServiceChanged.next("update")
          });
      }
    )

    this.dialogRef.close('Sorting of ' + this.dialogData.ReversePointer + ' done');
  }
}
