// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule, HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { FormCellBooleanDB } from './formcellboolean-db';

// insertion point for imports

@Injectable({
  providedIn: 'root'
})
export class FormCellBooleanService {

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  FormCellBooleanServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private formcellbooleansUrl: string

  constructor(
    private http: HttpClient,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.formcellbooleansUrl = origin + '/api/github.com/fullstack-lang/gongtable/go/v1/formcellbooleans';
  }

  /** GET formcellbooleans from the server */
  getFormCellBooleans(GONG__StackPath: string): Observable<FormCellBooleanDB[]> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    return this.http.get<FormCellBooleanDB[]>(this.formcellbooleansUrl, { params: params })
      .pipe(
        tap(),
		// tap(_ => this.log('fetched formcellbooleans')),
        catchError(this.handleError<FormCellBooleanDB[]>('getFormCellBooleans', []))
      );
  }

  /** GET formcellboolean by id. Will 404 if id not found */
  getFormCellBoolean(id: number, GONG__StackPath: string): Observable<FormCellBooleanDB> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    const url = `${this.formcellbooleansUrl}/${id}`;
    return this.http.get<FormCellBooleanDB>(url, { params: params }).pipe(
      // tap(_ => this.log(`fetched formcellboolean id=${id}`)),
      catchError(this.handleError<FormCellBooleanDB>(`getFormCellBoolean id=${id}`))
    );
  }

  /** POST: add a new formcellboolean to the server */
  postFormCellBoolean(formcellbooleandb: FormCellBooleanDB, GONG__StackPath: string): Observable<FormCellBooleanDB> {

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<FormCellBooleanDB>(this.formcellbooleansUrl, formcellbooleandb, httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        // this.log(`posted formcellbooleandb id=${formcellbooleandb.ID}`)
      }),
      catchError(this.handleError<FormCellBooleanDB>('postFormCellBoolean'))
    );
  }

  /** DELETE: delete the formcellbooleandb from the server */
  deleteFormCellBoolean(formcellbooleandb: FormCellBooleanDB | number, GONG__StackPath: string): Observable<FormCellBooleanDB> {
    const id = typeof formcellbooleandb === 'number' ? formcellbooleandb : formcellbooleandb.ID;
    const url = `${this.formcellbooleansUrl}/${id}`;

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.delete<FormCellBooleanDB>(url, httpOptions).pipe(
      tap(_ => this.log(`deleted formcellbooleandb id=${id}`)),
      catchError(this.handleError<FormCellBooleanDB>('deleteFormCellBoolean'))
    );
  }

  /** PUT: update the formcellbooleandb on the server */
  updateFormCellBoolean(formcellbooleandb: FormCellBooleanDB, GONG__StackPath: string): Observable<FormCellBooleanDB> {
    const id = typeof formcellbooleandb === 'number' ? formcellbooleandb : formcellbooleandb.ID;
    const url = `${this.formcellbooleansUrl}/${id}`;

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.put<FormCellBooleanDB>(url, formcellbooleandb, httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        // this.log(`updated formcellbooleandb id=${formcellbooleandb.ID}`)
      }),
      catchError(this.handleError<FormCellBooleanDB>('updateFormCellBoolean'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation in FormCellBooleanService', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error("FormCellBooleanService" + error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {
      console.log(message)
  }
}
