// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule, HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { FormCellDB } from './formcell-db';

// insertion point for imports
import { FormCellStringDB } from './formcellstring-db'
import { FormCellFloat64DB } from './formcellfloat64-db'
import { FormCellIntDB } from './formcellint-db'
import { FormCellBooleanDB } from './formcellboolean-db'
import { FormDB } from './form-db'

@Injectable({
  providedIn: 'root'
})
export class FormCellService {

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  FormCellServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private formcellsUrl: string

  constructor(
    private http: HttpClient,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.formcellsUrl = origin + '/api/github.com/fullstack-lang/gongtable/go/v1/formcells';
  }

  /** GET formcells from the server */
  getFormCells(GONG__StackPath: string): Observable<FormCellDB[]> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    return this.http.get<FormCellDB[]>(this.formcellsUrl, { params: params })
      .pipe(
        tap(),
		// tap(_ => this.log('fetched formcells')),
        catchError(this.handleError<FormCellDB[]>('getFormCells', []))
      );
  }

  /** GET formcell by id. Will 404 if id not found */
  getFormCell(id: number, GONG__StackPath: string): Observable<FormCellDB> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    const url = `${this.formcellsUrl}/${id}`;
    return this.http.get<FormCellDB>(url, { params: params }).pipe(
      // tap(_ => this.log(`fetched formcell id=${id}`)),
      catchError(this.handleError<FormCellDB>(`getFormCell id=${id}`))
    );
  }

  /** POST: add a new formcell to the server */
  postFormCell(formcelldb: FormCellDB, GONG__StackPath: string): Observable<FormCellDB> {

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    formcelldb.FormCellString = new FormCellStringDB
    formcelldb.FormCellFloat64 = new FormCellFloat64DB
    formcelldb.FormCellInt = new FormCellIntDB
    formcelldb.FormCellBool = new FormCellBooleanDB
    let _Form_FormCells_reverse = formcelldb.Form_FormCells_reverse
    formcelldb.Form_FormCells_reverse = new FormDB

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<FormCellDB>(this.formcellsUrl, formcelldb, httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        formcelldb.Form_FormCells_reverse = _Form_FormCells_reverse
        // this.log(`posted formcelldb id=${formcelldb.ID}`)
      }),
      catchError(this.handleError<FormCellDB>('postFormCell'))
    );
  }

  /** DELETE: delete the formcelldb from the server */
  deleteFormCell(formcelldb: FormCellDB | number, GONG__StackPath: string): Observable<FormCellDB> {
    const id = typeof formcelldb === 'number' ? formcelldb : formcelldb.ID;
    const url = `${this.formcellsUrl}/${id}`;

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.delete<FormCellDB>(url, httpOptions).pipe(
      tap(_ => this.log(`deleted formcelldb id=${id}`)),
      catchError(this.handleError<FormCellDB>('deleteFormCell'))
    );
  }

  /** PUT: update the formcelldb on the server */
  updateFormCell(formcelldb: FormCellDB, GONG__StackPath: string): Observable<FormCellDB> {
    const id = typeof formcelldb === 'number' ? formcelldb : formcelldb.ID;
    const url = `${this.formcellsUrl}/${id}`;

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    formcelldb.FormCellString = new FormCellStringDB
    formcelldb.FormCellFloat64 = new FormCellFloat64DB
    formcelldb.FormCellInt = new FormCellIntDB
    formcelldb.FormCellBool = new FormCellBooleanDB
    let _Form_FormCells_reverse = formcelldb.Form_FormCells_reverse
    formcelldb.Form_FormCells_reverse = new FormDB

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.put<FormCellDB>(url, formcelldb, httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        formcelldb.Form_FormCells_reverse = _Form_FormCells_reverse
        // this.log(`updated formcelldb id=${formcelldb.ID}`)
      }),
      catchError(this.handleError<FormCellDB>('updateFormCell'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation in FormCellService', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error("FormCellService" + error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {
      console.log(message)
  }
}
