// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule, HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { FormDB } from './form-db';

// insertion point for imports

@Injectable({
  providedIn: 'root'
})
export class FormService {

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  FormServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private formsUrl: string

  constructor(
    private http: HttpClient,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.formsUrl = origin + '/api/github.com/fullstack-lang/gongtable/go/v1/forms';
  }

  /** GET forms from the server */
  getForms(GONG__StackPath: string): Observable<FormDB[]> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    return this.http.get<FormDB[]>(this.formsUrl, { params: params })
      .pipe(
        tap(),
		// tap(_ => this.log('fetched forms')),
        catchError(this.handleError<FormDB[]>('getForms', []))
      );
  }

  /** GET form by id. Will 404 if id not found */
  getForm(id: number, GONG__StackPath: string): Observable<FormDB> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    const url = `${this.formsUrl}/${id}`;
    return this.http.get<FormDB>(url, { params: params }).pipe(
      // tap(_ => this.log(`fetched form id=${id}`)),
      catchError(this.handleError<FormDB>(`getForm id=${id}`))
    );
  }

  /** POST: add a new form to the server */
  postForm(formdb: FormDB, GONG__StackPath: string): Observable<FormDB> {

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    formdb.FormCells = []

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<FormDB>(this.formsUrl, formdb, httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        // this.log(`posted formdb id=${formdb.ID}`)
      }),
      catchError(this.handleError<FormDB>('postForm'))
    );
  }

  /** DELETE: delete the formdb from the server */
  deleteForm(formdb: FormDB | number, GONG__StackPath: string): Observable<FormDB> {
    const id = typeof formdb === 'number' ? formdb : formdb.ID;
    const url = `${this.formsUrl}/${id}`;

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.delete<FormDB>(url, httpOptions).pipe(
      tap(_ => this.log(`deleted formdb id=${id}`)),
      catchError(this.handleError<FormDB>('deleteForm'))
    );
  }

  /** PUT: update the formdb on the server */
  updateForm(formdb: FormDB, GONG__StackPath: string): Observable<FormDB> {
    const id = typeof formdb === 'number' ? formdb : formdb.ID;
    const url = `${this.formsUrl}/${id}`;

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    formdb.FormCells = []

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.put<FormDB>(url, formdb, httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        // this.log(`updated formdb id=${formdb.ID}`)
      }),
      catchError(this.handleError<FormDB>('updateForm'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation in FormService', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error("FormService" + error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {
      console.log(message)
  }
}
