// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule, HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { FormFieldBooleanDB } from './formfieldboolean-db';

// insertion point for imports

@Injectable({
  providedIn: 'root'
})
export class FormFieldBooleanService {

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  FormFieldBooleanServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private formfieldbooleansUrl: string

  constructor(
    private http: HttpClient,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.formfieldbooleansUrl = origin + '/api/github.com/fullstack-lang/gongtable/go/v1/formfieldbooleans';
  }

  /** GET formfieldbooleans from the server */
  getFormFieldBooleans(GONG__StackPath: string): Observable<FormFieldBooleanDB[]> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    return this.http.get<FormFieldBooleanDB[]>(this.formfieldbooleansUrl, { params: params })
      .pipe(
        tap(),
		// tap(_ => this.log('fetched formfieldbooleans')),
        catchError(this.handleError<FormFieldBooleanDB[]>('getFormFieldBooleans', []))
      );
  }

  /** GET formfieldboolean by id. Will 404 if id not found */
  getFormFieldBoolean(id: number, GONG__StackPath: string): Observable<FormFieldBooleanDB> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    const url = `${this.formfieldbooleansUrl}/${id}`;
    return this.http.get<FormFieldBooleanDB>(url, { params: params }).pipe(
      // tap(_ => this.log(`fetched formfieldboolean id=${id}`)),
      catchError(this.handleError<FormFieldBooleanDB>(`getFormFieldBoolean id=${id}`))
    );
  }

  /** POST: add a new formfieldboolean to the server */
  postFormFieldBoolean(formfieldbooleandb: FormFieldBooleanDB, GONG__StackPath: string): Observable<FormFieldBooleanDB> {

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<FormFieldBooleanDB>(this.formfieldbooleansUrl, formfieldbooleandb, httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        // this.log(`posted formfieldbooleandb id=${formfieldbooleandb.ID}`)
      }),
      catchError(this.handleError<FormFieldBooleanDB>('postFormFieldBoolean'))
    );
  }

  /** DELETE: delete the formfieldbooleandb from the server */
  deleteFormFieldBoolean(formfieldbooleandb: FormFieldBooleanDB | number, GONG__StackPath: string): Observable<FormFieldBooleanDB> {
    const id = typeof formfieldbooleandb === 'number' ? formfieldbooleandb : formfieldbooleandb.ID;
    const url = `${this.formfieldbooleansUrl}/${id}`;

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.delete<FormFieldBooleanDB>(url, httpOptions).pipe(
      tap(_ => this.log(`deleted formfieldbooleandb id=${id}`)),
      catchError(this.handleError<FormFieldBooleanDB>('deleteFormFieldBoolean'))
    );
  }

  /** PUT: update the formfieldbooleandb on the server */
  updateFormFieldBoolean(formfieldbooleandb: FormFieldBooleanDB, GONG__StackPath: string): Observable<FormFieldBooleanDB> {
    const id = typeof formfieldbooleandb === 'number' ? formfieldbooleandb : formfieldbooleandb.ID;
    const url = `${this.formfieldbooleansUrl}/${id}`;

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.put<FormFieldBooleanDB>(url, formfieldbooleandb, httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        // this.log(`updated formfieldbooleandb id=${formfieldbooleandb.ID}`)
      }),
      catchError(this.handleError<FormFieldBooleanDB>('updateFormFieldBoolean'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation in FormFieldBooleanService', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error("FormFieldBooleanService" + error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {
      console.log(message)
  }
}
